#ifndef DEBUGPARAMS_H_INCLUDED
#define DEBUGPARAMS_H_INCLUDED

#ifndef DEBUG_MESSAGES_SHOW
//#define DEBUG_MESSAGES_SHOW
//#include <iostream>
#endif // DEBUG_MESSAGES_SHOW

#endif // DEBUGPARAMS_H_INCLUDED
